services:
    mysql:
        image: mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        volumes:
            - ./mysql/data:/docker-entrypoint-initdb.d
        ports:
            - 43306:3306

    dbclient:
        image: phpmyadmin/phpmyadmin
        container_name: dbclient
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
        links:
            - mysql
        ports:
            - 4200:80
        volumes:
            - ./dbclient/sessions:/sessions
        depends_on:
            - mysql

    spring:
        image: openjdk:17
        container_name: spring
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
        working_dir: /app
        tty: true
        command: >
            /bin/sh -c '
            microdnf install findutils &&
            ./gradlew build &&
            java -jar build/libs/demo-0.0.1-SNAPSHOT.jar
            '
        volumes:
            - ./spring:/app
        ports:
            - 48080:8080
        depends_on:
            - mysql
